# Command to start on workspace startup (optional)
tasks:
  - command: "cd && npm install -g npm && npm install -g --unsafe-perm node-red node-red-dashboard qrcode-terminal && mkdir .node-red && ln -s /workspace/nodered-online-reaction-app/flow.json ./.node-red/ && echo $GITPOD_WORKSPACE_URL | awk -F// '{print $1 \"//1880-\" $2 \"/ui\"}' | qrcode-terminal && node-red flow.json"
# Ports to expose on workspace startup (optional)
ports:
  - port: 1880
    onOpen: open-preview
    
